# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/local/bin/cmake

# The command to remove a file.
RM = /opt/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/masoudshokri/Documents/GitHub/particlizationCalc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/masoudshokri/Documents/GitHub/particlizationCalc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/opt/local/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/opt/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/opt/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/masoudshokri/Documents/GitHub/particlizationCalc/CMakeFiles /Users/masoudshokri/Documents/GitHub/particlizationCalc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/masoudshokri/Documents/GitHub/particlizationCalc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named test_utils

# Build rule for target.
test_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_utils
.PHONY : test_utils

# fast build rule for target.
test_utils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/build
.PHONY : test_utils/fast

#=============================================================================
# Target rules for targets named test_cells

# Build rule for target.
test_cells: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_cells
.PHONY : test_cells

# fast build rule for target.
test_cells/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/build
.PHONY : test_cells/fast

#=============================================================================
# Target rules for targets named test_engine_design

# Build rule for target.
test_engine_design: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_engine_design
.PHONY : test_engine_design

# fast build rule for target.
test_engine_design/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/build
.PHONY : test_engine_design/fast

#=============================================================================
# Target rules for targets named bench_utils

# Build rule for target.
bench_utils: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 bench_utils
.PHONY : bench_utils

# fast build rule for target.
bench_utils/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_utils.dir/build.make CMakeFiles/bench_utils.dir/build
.PHONY : bench_utils/fast

#=============================================================================
# Target rules for targets named calc

# Build rule for target.
calc: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 calc
.PHONY : calc

# fast build rule for target.
calc/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/build
.PHONY : calc/fast

#=============================================================================
# Target rules for targets named gmock

# Build rule for target.
gmock: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock
.PHONY : gmock

# fast build rule for target.
gmock/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock.dir/build
.PHONY : gmock/fast

#=============================================================================
# Target rules for targets named gmock_main

# Build rule for target.
gmock_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gmock_main
.PHONY : gmock_main

# fast build rule for target.
gmock_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build.make _deps/googletest-build/googlemock/CMakeFiles/gmock_main.dir/build
.PHONY : gmock_main/fast

#=============================================================================
# Target rules for targets named gtest

# Build rule for target.
gtest: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest
.PHONY : gtest

# fast build rule for target.
gtest/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest.dir/build
.PHONY : gtest/fast

#=============================================================================
# Target rules for targets named gtest_main

# Build rule for target.
gtest_main: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gtest_main
.PHONY : gtest_main

# fast build rule for target.
gtest_main/fast:
	$(MAKE) $(MAKESILENT) -f _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build.make _deps/googletest-build/googletest/CMakeFiles/gtest_main.dir/build
.PHONY : gtest_main/fast

src/element.o: src/element.cpp.o
.PHONY : src/element.o

# target to build an object file
src/element.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/element.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/element.cpp.o
.PHONY : src/element.cpp.o

src/element.i: src/element.cpp.i
.PHONY : src/element.i

# target to preprocess a source file
src/element.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/element.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/element.cpp.i
.PHONY : src/element.cpp.i

src/element.s: src/element.cpp.s
.PHONY : src/element.s

# target to generate assembly for a file
src/element.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/element.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/element.cpp.s
.PHONY : src/element.cpp.s

src/fcell.o: src/fcell.cpp.o
.PHONY : src/fcell.o

# target to build an object file
src/fcell.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/fcell.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/fcell.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/fcell.cpp.o
.PHONY : src/fcell.cpp.o

src/fcell.i: src/fcell.cpp.i
.PHONY : src/fcell.i

# target to preprocess a source file
src/fcell.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/fcell.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/fcell.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/fcell.cpp.i
.PHONY : src/fcell.cpp.i

src/fcell.s: src/fcell.cpp.s
.PHONY : src/fcell.s

# target to generate assembly for a file
src/fcell.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/fcell.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/fcell.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/fcell.cpp.s
.PHONY : src/fcell.cpp.s

src/geometry.o: src/geometry.cpp.o
.PHONY : src/geometry.o

# target to build an object file
src/geometry.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/geometry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/geometry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_utils.dir/build.make CMakeFiles/bench_utils.dir/src/geometry.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/geometry.cpp.o
.PHONY : src/geometry.cpp.o

src/geometry.i: src/geometry.cpp.i
.PHONY : src/geometry.i

# target to preprocess a source file
src/geometry.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/geometry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/geometry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_utils.dir/build.make CMakeFiles/bench_utils.dir/src/geometry.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/geometry.cpp.i
.PHONY : src/geometry.cpp.i

src/geometry.s: src/geometry.cpp.s
.PHONY : src/geometry.s

# target to generate assembly for a file
src/geometry.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/geometry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/geometry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_utils.dir/build.make CMakeFiles/bench_utils.dir/src/geometry.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/geometry.cpp.s
.PHONY : src/geometry.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/utils.o: src/utils.cpp.o
.PHONY : src/utils.o

# target to build an object file
src/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/src/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_utils.dir/build.make CMakeFiles/bench_utils.dir/src/utils.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/utils.cpp.o
.PHONY : src/utils.cpp.o

src/utils.i: src/utils.cpp.i
.PHONY : src/utils.i

# target to preprocess a source file
src/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/src/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_utils.dir/build.make CMakeFiles/bench_utils.dir/src/utils.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/utils.cpp.i
.PHONY : src/utils.cpp.i

src/utils.s: src/utils.cpp.s
.PHONY : src/utils.s

# target to generate assembly for a file
src/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/src/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/src/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/src/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_utils.dir/build.make CMakeFiles/bench_utils.dir/src/utils.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/calc.dir/build.make CMakeFiles/calc.dir/src/utils.cpp.s
.PHONY : src/utils.cpp.s

test/bench_utils.o: test/bench_utils.cpp.o
.PHONY : test/bench_utils.o

# target to build an object file
test/bench_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_utils.dir/build.make CMakeFiles/bench_utils.dir/test/bench_utils.cpp.o
.PHONY : test/bench_utils.cpp.o

test/bench_utils.i: test/bench_utils.cpp.i
.PHONY : test/bench_utils.i

# target to preprocess a source file
test/bench_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_utils.dir/build.make CMakeFiles/bench_utils.dir/test/bench_utils.cpp.i
.PHONY : test/bench_utils.cpp.i

test/bench_utils.s: test/bench_utils.cpp.s
.PHONY : test/bench_utils.s

# target to generate assembly for a file
test/bench_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/bench_utils.dir/build.make CMakeFiles/bench_utils.dir/test/bench_utils.cpp.s
.PHONY : test/bench_utils.cpp.s

test/ibjorken.o: test/ibjorken.cpp.o
.PHONY : test/ibjorken.o

# target to build an object file
test/ibjorken.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/test/ibjorken.cpp.o
.PHONY : test/ibjorken.cpp.o

test/ibjorken.i: test/ibjorken.cpp.i
.PHONY : test/ibjorken.i

# target to preprocess a source file
test/ibjorken.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/test/ibjorken.cpp.i
.PHONY : test/ibjorken.cpp.i

test/ibjorken.s: test/ibjorken.cpp.s
.PHONY : test/ibjorken.s

# target to generate assembly for a file
test/ibjorken.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/test/ibjorken.cpp.s
.PHONY : test/ibjorken.cpp.s

test/my_engine.o: test/my_engine.cpp.o
.PHONY : test/my_engine.o

# target to build an object file
test/my_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/test/my_engine.cpp.o
.PHONY : test/my_engine.cpp.o

test/my_engine.i: test/my_engine.cpp.i
.PHONY : test/my_engine.i

# target to preprocess a source file
test/my_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/test/my_engine.cpp.i
.PHONY : test/my_engine.cpp.i

test/my_engine.s: test/my_engine.cpp.s
.PHONY : test/my_engine.s

# target to generate assembly for a file
test/my_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/test/my_engine.cpp.s
.PHONY : test/my_engine.cpp.s

test/test_cells.o: test/test_cells.cpp.o
.PHONY : test/test_cells.o

# target to build an object file
test/test_cells.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/test/test_cells.cpp.o
.PHONY : test/test_cells.cpp.o

test/test_cells.i: test/test_cells.cpp.i
.PHONY : test/test_cells.i

# target to preprocess a source file
test/test_cells.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/test/test_cells.cpp.i
.PHONY : test/test_cells.cpp.i

test/test_cells.s: test/test_cells.cpp.s
.PHONY : test/test_cells.s

# target to generate assembly for a file
test/test_cells.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_cells.dir/build.make CMakeFiles/test_cells.dir/test/test_cells.cpp.s
.PHONY : test/test_cells.cpp.s

test/test_engine_design.o: test/test_engine_design.cpp.o
.PHONY : test/test_engine_design.o

# target to build an object file
test/test_engine_design.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/test/test_engine_design.cpp.o
.PHONY : test/test_engine_design.cpp.o

test/test_engine_design.i: test/test_engine_design.cpp.i
.PHONY : test/test_engine_design.i

# target to preprocess a source file
test/test_engine_design.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/test/test_engine_design.cpp.i
.PHONY : test/test_engine_design.cpp.i

test/test_engine_design.s: test/test_engine_design.cpp.s
.PHONY : test/test_engine_design.s

# target to generate assembly for a file
test/test_engine_design.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_engine_design.dir/build.make CMakeFiles/test_engine_design.dir/test/test_engine_design.cpp.s
.PHONY : test/test_engine_design.cpp.s

test/test_utils.o: test/test_utils.cpp.o
.PHONY : test/test_utils.o

# target to build an object file
test/test_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/test/test_utils.cpp.o
.PHONY : test/test_utils.cpp.o

test/test_utils.i: test/test_utils.cpp.i
.PHONY : test/test_utils.i

# target to preprocess a source file
test/test_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/test/test_utils.cpp.i
.PHONY : test/test_utils.cpp.i

test/test_utils.s: test/test_utils.cpp.s
.PHONY : test/test_utils.s

# target to generate assembly for a file
test/test_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_utils.dir/build.make CMakeFiles/test_utils.dir/test/test_utils.cpp.s
.PHONY : test/test_utils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... bench_utils"
	@echo "... calc"
	@echo "... gmock"
	@echo "... gmock_main"
	@echo "... gtest"
	@echo "... gtest_main"
	@echo "... test_cells"
	@echo "... test_engine_design"
	@echo "... test_utils"
	@echo "... src/element.o"
	@echo "... src/element.i"
	@echo "... src/element.s"
	@echo "... src/fcell.o"
	@echo "... src/fcell.i"
	@echo "... src/fcell.s"
	@echo "... src/geometry.o"
	@echo "... src/geometry.i"
	@echo "... src/geometry.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/utils.o"
	@echo "... src/utils.i"
	@echo "... src/utils.s"
	@echo "... test/bench_utils.o"
	@echo "... test/bench_utils.i"
	@echo "... test/bench_utils.s"
	@echo "... test/ibjorken.o"
	@echo "... test/ibjorken.i"
	@echo "... test/ibjorken.s"
	@echo "... test/my_engine.o"
	@echo "... test/my_engine.i"
	@echo "... test/my_engine.s"
	@echo "... test/test_cells.o"
	@echo "... test/test_cells.i"
	@echo "... test/test_cells.s"
	@echo "... test/test_engine_design.o"
	@echo "... test/test_engine_design.i"
	@echo "... test/test_engine_design.s"
	@echo "... test/test_utils.o"
	@echo "... test/test_utils.i"
	@echo "... test/test_utils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

