if(EXISTS "/Users/masoudshokri/Documents/GitHub/particlizationCalc/test_build/test_utils[1]_tests.cmake")
  include("/Users/masoudshokri/Documents/GitHub/particlizationCalc/test_build/test_utils[1]_tests.cmake")
else()
  add_test(test_utils_NOT_BUILT test_utils_NOT_BUILT)
endif()
